const azdev = require('azure-devops-node-api');

class AzureDevOpsService {
  constructor(config) {
    this.config = config;
    this.orgUrl = config.orgUrl;
    this.token = config.token;
    this.project = config.project;
    this.connection = null;
  }

  /**
   * Initialize connection to Azure DevOps
   */
  async initialize() {
    const authHandler = azdev.getPersonalAccessTokenHandler(this.token);
    this.connection = new azdev.WebApi(this.orgUrl, authHandler);
    console.log('Connected to Azure DevOps');
  }

  /**
   * Create a user story work item with RCA and recommendations
   * @param {string} buildId - The build ID
   * @param {string} rca - Root cause analysis
   * @param {string} recommendations - Recommended fixes
   * @param {string} buildUrl - URL to the failed build
   * @returns {Promise<Object>} - Created work item
   */
  async createWorkItem(buildId, rca, recommendations, buildUrl) {
    if (!this.connection) {
      await this.initialize();
    }

    const witApi = await this.connection.getWorkItemTrackingApi();

    const title = `Build Failure Analysis - Build #${buildId}`;
    const description = this.formatWorkItemDescription(rca, recommendations, buildUrl);

    const patchDocument = [
      {
        op: 'add',
        path: '/fields/System.Title',
        value: title
      },
      {
        op: 'add',
        path: '/fields/System.Description',
        value: description
      },
      {
        op: 'add',
        path: '/fields/System.Tags',
        value: 'build-failure; automated-analysis'
      },
      {
        op: 'add',
        path: '/fields/Microsoft.VSTS.Common.Priority',
        value: 1
      }
    ];

    try {
      const workItem = await witApi.createWorkItem(
        null,
        patchDocument,
        this.project,
        'User Story'
      );

      console.log(`Work item created successfully: ${workItem.id}`);
      return {
        id: workItem.id,
        url: workItem._links.html.href
      };
    } catch (error) {
      console.error('Error creating work item:', error);
      throw new Error(`Failed to create work item: ${error.message}`);
    }
  }

  /**
   * Format work item description with RCA and recommendations
   * @param {string} rca - Root cause analysis
   * @param {string} recommendations - Recommended fixes
   * @param {string} buildUrl - URL to the failed build
   * @returns {string} - Formatted description in HTML
   */
  formatWorkItemDescription(rca, recommendations, buildUrl) {
    return `<div>
<h2>Build Failure Analysis</h2>
<p>This work item was automatically created by Build-Fixer to track a build failure.</p>

<h3>Build Information</h3>
<p><strong>Build URL:</strong> <a href="${buildUrl}">${buildUrl}</a></p>

<h3>Root Cause Analysis</h3>
<div>${this.escapeHtml(rca).replace(/\n/g, '<br/>')}</div>

<h3>Recommended Fixes</h3>
<div>${this.escapeHtml(recommendations).replace(/\n/g, '<br/>')}</div>

<hr/>
<p><em>Generated by Build-Fixer - Automated Build Analysis Tool</em></p>
</div>`;
  }

  /**
   * Escape HTML special characters
   * @param {string} text - Text to escape
   * @returns {string} - Escaped text
   */
  escapeHtml(text) {
    const map = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;'
    };
    return text.replace(/[&<>"']/g, m => map[m]);
  }
}

module.exports = AzureDevOpsService;
